### ISSUE TITLE
New update is slow!

### ISSUE THREAD

**Issue by admincode1** [medyas/flutter_qiblah#21]
I upgraded today to 2.0.2, the compass move slower than normal.
Tested on Samsung S20.

**Comment by medyas** [comment]
well i can't reproduce this. Also i have not made any modification to the plugin code, just upgraded the flutter_compass version so maybe this is related to it. But based on my emulator tests it works same as always.

**Comment by admincode1** [comment]
Most likely caused by flutter_compass new upgrade.

**Comment by iqfareez** [comment]
I fix the issue by override the flutter_compass dependencies:

```yaml
dependency_overrides:
  flutter_compass:
    git: https://github.com/hemanthrajv/flutter_compass.git
```

Commit ref: `8f753aefe76b08092c0e5bda93775ade8fe66016`
